# Generated by Django 6.0.2 on 2026-03-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutname', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='In Minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.workout')),
            ],
        ),
    ]
