# Generated by Django 6.0.2 on 2026-03-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_workout_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='training',
            new_name='workout',
        ),
    ]
